### ISSUE TITLE
Can't use on Silex 1.x

### ISSUE THREAD

**Issue by jcambien** [jeromemacias/Silex-Debug#1]
Hi,

I don't know if this the right place for this problem but you may have the solution.
I'm trying to use this provider on Silex 1.x but this version is running symfony/http-kernel 2.5.x.
Because it's the only stable version, i can't go on the 2.0 dev.

This is what i got when trying to install this package : 

```
composer require jeromemacias/silex-debug ~1.0@dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jeromemacias/silex-debug ~1.0@dev -> satisfiable by jeromemacias/silex-debug[1.0.x-dev].
    - Conclusion: remove symfony/http-kernel v2.5.8
    - jeromemacias/silex-debug 1.0.x-dev requires symfony/debug-bundle ~2.6 -> satisfiable by symfony/debug-bundle[v2.6.0, v2.6.1].
    - symfony/debug-bundle v2.6.0 requires symfony/http-kernel ~2.6 -> satisfiable by symfony/http-kernel[v2.6.0, v2.6.1].
    - symfony/debug-bundle v2.6.1 requires symfony/http-kernel ~2.6 -> satisfiable by symfony/http-kernel[v2.6.0, v2.6.1].
    - Can only install one of: symfony/http-kernel[v2.6.0, v2.5.8].
    - Can only install one of: symfony/http-kernel[v2.6.1, v2.5.8].
    - Installation request for symfony/http-kernel == 2.5.8.0 -> satisfiable by symfony/http-kernel[v2.5.8].


Installation failed, reverting ./composer.json to its original content.
```

After some researches, i discovered that symfony/debug-bundle is running only with 2.6 or greater, that explains the version conflit.

Is there any solution for Silex 1.0 or I should wait for next Silex major version ? 
Thank you.

**Comment by jeromemacias** [comment]
You can use Silex dev version by requiring `silex/silex: 1.2@dev` in your `composer.json`.
Silex `1.2` branch is stable enough to be use.

**Comment by jcambien** [comment]
This composer.json worked for me : 

```
{
  "require": {
    "silex/silex": "~1.2@dev",
    "jeromemacias/silex-debug": "~1.0@dev"
  }
}
```

I had to use `~` on each versions, the other way it does not pass.
Thanks for the help !

**Comment by jcambien** [comment]
Additional note : In my working example, you will notice that Symfony 2.7.X will be installed in replacement of 2.6 because of the `@dev`. Add this to your composer.json to prefer stable version :

```
"minimum-stability": "dev",
"prefer-stable": true
```
